### ISSUE TITLE
you must set the 'items' attribute

### ISSUE THREAD

**Issue by mluis** [souly1/ion-select-picker#2]
Hello, I'm using the following HTML code:

`<input style="text-align: right; background-color: inherit;" type="text" items="lsData.entityEmployees.commTypes" ng-model="lsData.entityEmployees.selectedCommType" ng-value="Value" ng-readonly="true" ion-select-picker>` 

With the 'items' {{ lsData.entityEmployees.commTypes }}

`[ { "Value": "E-Mail" }, { "Value": "SMS" } ]`

And getting the following error:
`
?ionicplatform=ios:28 you must set the "items" attribute!console.(anonymous function) @ ?ionicplatform=ios:28(anonymous function) @ ionic.bundle.js:21162F @ ionSelectPicker.min.js:2f @ ionSelectPicker.min.js:2(anonymous function) @ ionic.bundle.js:17476invokeLinkFn @ ionic.bundle.js:17482nodeLinkFn @ ionic.bundle.js:16982compositeLinkFn @ ionic.bundle.js:16373compositeLinkFn @ ionic.bundle.js:16377compositeLinkFn @ ionic.bundle.js:16377nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16373nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16373compositeLinkFn @ ionic.bundle.js:16377compositeLinkFn @ ionic.bundle.js:16377compositeLinkFn @ ionic.bundle.js:16377nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16373nodeLinkFn @ ionic.bundle.js:16977(anonymous function) @ ionic.bundle.js:17212processQueue @ ionic.bundle.js:23399(anonymous function) @ ionic.bundle.js:23415$eval @ ionic.bundle.js:24678$digest @ ionic.bundle.js:24489$apply @ ionic.bundle.js:24783done @ ionic.bundle.js:19196completeRequest @ ionic.bundle.js:19368requestLoaded @ ionic.bundle.js:19309
?ionicplatform=ios:28 Error: you must set the "items" attribute!
    at F (http://localhost:8100/lib/ion-selectpicker/ionSelectPicker.min.js:2:64732)
    at f (http://localhost:8100/lib/ion-selectpicker/ionSelectPicker.min.js:2:65837)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17476:44
    at invokeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17482:9)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16982:11)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16373:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16377:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16377:13)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16977:24)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16373:13) <input style="" type="text" items="lsData.entityEmployees.commTypes" ng-model="lsData.entityEmployees.selectedCommType" ng-value="Value" ng-readonly="true" ion-select-picker="" class="ng-pristine ng-untouched ng-valid">console.(anonymous function) @ ?ionicplatform=ios:28(anonymous function) @ ionic.bundle.js:21162(anonymous function) @ ionic.bundle.js:17941invokeLinkFn @ ionic.bundle.js:17484nodeLinkFn @ ionic.bundle.js:16982compositeLinkFn @ ionic.bundle.js:16373compositeLinkFn @ ionic.bundle.js:16377compositeLinkFn @ ionic.bundle.js:16377nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16373nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16373compositeLinkFn @ ionic.bundle.js:16377compositeLinkFn @ ionic.bundle.js:16377compositeLinkFn @ ionic.bundle.js:16377nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16373nodeLinkFn @ ionic.bundle.js:16977(anonymous function) @ ionic.bundle.js:17212processQueue @ ionic.bundle.js:23399(anonymous function) @ ionic.bundle.js:23415$eval @ ionic.bundle.js:24678$digest @ ionic.bundle.js:24489$apply @ ionic.bundle.js:24783done @ ionic.bundle.js:19196completeRequest @ ionic.bundle.js:19368requestLoaded @ ionic.bundle.js:19309
?ionicplatform=ios:28 Uncaught TypeError: y.openDrawer is not a function http://localhost:8100/lib/ion-selectpicker/ionSelectPicker.min.js Line: 2console.(anonymous function) @ ?ionicplatform=ios:28window.onerror @ ?ionicplatform=ios:12triggerMouseEvent @ ionic.bundle.js:2870tapClick @ ionic.bundle.js:2859tapMouseUp @ ionic.bundle.js:2932
ionSelectPicker.min.js:2 Uncaught TypeError: y.openDrawer is not a function`

**Comment by souly1** [comment]
Hi @mluis , I'll look into the  issue tomorrow, but regarding this one:
items must be set to an array, even an empty one, and in this case it is set to `lsData.entityEmployees.commTypes` which probably is unknown or null, correct?

**Comment by mluis** [comment]
No, it is set to [ { "Value": "SMS" }, {"Value":"E-Mail"} ].

Do you have any news on this?

Thank you

**Comment by souly1** [comment]
Hi, 
This is what i ran to simulate your situation when initializing my controller:

``` javascript
$scope.lsData = {entityEmployees:{commType:{}}};
        $scope.lsData.entityEmployees.commTypes = [
            { "Value": "SMS" },
            {"Value":"E-Mail"}
        ];
```

The HTML is copy/paste from what you wrote above.

In this situation it ran as expected, so let's try to breakdown the issue after you run this simple example:
Could you perhaps copy/paste the javascript code above in initialization of your controller and see if works then?
P.S It is written in the error message you attached platform iOS, did you check if it runs in the webBrowser/android?

Thanks

**Comment by mluis** [comment]
Hi,

I say that `$scope.lsData.entityEmployees.commTypes` is populated because {{lsData.entityEmployees.commTypes}} in the HTML show its content as the one I wrote above.

I'm using `ionic serve` functionality to test the plugin and so it was tested in the iOS side running in the browser but I didn't tried in the Android side.

In the initialization of the controller there is `$scope.lsData = lsData` injected in the controller.

**Comment by souly1** [comment]
Hi,
I have no doubt that you're initializing `commTypes` but I'm thinking perhaps it could be connected to the stage it is initialized in the Angular lifecycle, that's why I'm offering to create a simple object at the moment, just to see that works.
Anyhow, I've just issued a new version to avoid this issue (instead of an exception just show a warning message) - v2.0.2.
Download it, try it out and tell me if it solved the issue.

Thanks

**Comment by mluis** [comment]
Hi!

It seems to be working perfectly.

And here's what is happening in the console:

```
info: "items" attribute valid!
warning: "you must set the "items" attribute!"
info: "items" attribute valid!
```

One more happy customer. :)
Thanks.

**Comment by souly1** [comment]
Glad to hear that everything worked out @mluis ,
Enjoy!
